spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://springboot-db.cszagrzyjprb.ap-northeast-2.rds.amazonaws.com:3306/ewha-plate?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: ayo_db
    password: ayong2gadb

  #  mustache:
  #    suffix: .mustache

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create || update || none -> create 하면 실행할 때마다 테이블을 새로 만듬(나중엔 update로 변경해야 함)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # Entity 만들 때, 변수명 그대로
        # 만약 SpringPhysicalNamingStrategy 를 쓰면 myEmail -> my_email 로 됨, 우리는 그대로 만들것임..
      use-new-id-generator-mappings: false #
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

